import pandas as pd
import matplotlib.pyplot as plt
read_csv = pd.read_csv('video_games_dataset.csv')
'''finding out top 10 games best-selling'''
top_10 = read_csv.sort_values('Global_Sales' , ascending=True)
tail_10 = top_10.tail(10)
plt.figure(figsize=(14,6))
plt.bar(tail_10['Name'] , tail_10['Global_Sales'] , color = 'hotpink', width=0.5)
plt.xlabel("Games Names")
plt.ylabel("Global Sales")
plt.title("Top 10 Best-Selling Video Games")
plt.xticks(rotation = 45 , ha = 'right')
plt.yticks(rotation = 45 , va = 'top')
plt.grid(True)
plt.tight_layout()
plt.show()
'''now finding the total sale of plateform highest sale'''
platform = read_csv.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False)
print(platform)
plt.figure(figsize = (14,8))
plt.title("Highest Sales Platforms")
plt.bar(platform.index , platform.values , color = 'lightblue' , width = 0.75)
plt.xlabel("Platform")
plt.xticks(rotation= 45 , ha = 'right')
plt.ylabel("total global Sales")
plt.yticks(rotation = 45 , va = 'top')
plt.tight_layout()
plt.show()
'''now finding genre with highest average sales'''
genre = read_csv.groupby('Genre')['Global_Sales'].mean().sort_values(ascending=False)
# print(genre)
plt.figure(figsize=(12,4))
plt.title("Genre With Highest Average Sales")
plt.xlabel("Genre")
plt.xticks(rotation = 45 , ha = 'right')
plt.ylabel('Average Global Sales')
plt.yticks(rotation = 45 , va = 'top')
plt.bar(genre.index , genre.values , color = 'purple' , width = 0.75)
plt.tight_layout()
plt.show()
'''now finding how many games were released each year'''
year = read_csv['Year'].value_counts().sort_index()
# print(year)
plt.figure(figsize = (14,6))
plt.title('Numbers of Games released Each year')
plt.xlabel('Year')
plt.xticks(range(min(year.index),max(year.index)+1),rotation = 45 ,ha='right')
plt.ylabel('Number of Game Released')
plt.yticks(rotation = 45 , va = 'top')
plt.bar(year.index , year.values , color = 'red' , width = 0.75)
plt.tight_layout()
plt.show()
'''now finding that which publisher has the most games'''
publisher = read_csv['Publisher'].value_counts()
print(publisher)
plt.figure(figsize = (14,6))
plt.title('Publishers with Most Games')
plt.xlabel('Publisher')
plt.xticks(rotation = 45 , ha = 'right')
plt.ylabel('Number of Games Pubvlishered')
plt.yticks(rotation = 45 , va = 'top')
plt.bar(publisher.index , publisher.values , color ='purple' , width  =0.25)
plt.tight_layout()
plt.show()